config/urls.py
"""Main URLs module."""

from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin


# import ipdb; ipdb.set_trace()

urlpatterns = [
    # Django Admin
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include(("src.home.urls", "home"), namespace="home")),
    path("store/", include(("src.store.urls", "store"), namespace="store")),
    path("cart/", include(("src.carts.urls", "cart"), namespace="cart")),
    path("accounts/", include(("src.accounts.urls", "accounts"), namespace="accounts")),
    path("orders/", include(("src.orders.urls", "orders"), namespace="orders")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.cart, name="home"),
    path("add_cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path(
        "remove_cart/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart,
        name="remove_cart",
    ),
    path(
        "remove_cart_item/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
    path('checkout/', views.checkout, name='checkout'),

]

src/home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
]

src/orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("place_order/", views.place_order, name="place_order"),
    path("payments/", views.payments, name="payments"),
    path("order_complete/", views.order_complete, name="order_complete"),
]

src/store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.store, name="home"),
    path("category/<slug:category_slug>/", views.store, name="products_by_category"),
    path(
        "category/<slug:category_slug>/<slug:product_slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path("search/", views.search, name="search"),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),

]

src/orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "first_name",
            "last_name",
            "phone",
            "email",
            "address_line_1",
            "address_line_2",
            "country",
            "state",
            "city",
            "order_note",
        ]

src/store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ["subject", "review", "rating"]

src/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required

import requests

# Verification email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

from src.carts.views import _cart_id
from src.carts.models import Cart, CartItem
from src.orders.models import Order, OrderProduct

from .models import Account, UserProfile
from .forms import RegistrationForm, UserForm, UserProfileForm


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            phone_number = form.cleaned_data["phone_number"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            username = email.split("@")[0]
            user = Account.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=username,
                password=password,
            )
            user.phone_number = phone_number
            user.save()

            # Create a user profile
            profile = UserProfile()
            profile.user_id = user.id
            profile.profile_picture = "default/default-user.png"
            profile.save()

            # USER ACTIVATION
            current_site = get_current_site(request)
            mail_subject = "Please activate your account"
            message = render_to_string(
                "accounts/account_verification_email.html",
                {
                    "user": user,
                    "domain": current_site,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": default_token_generator.make_token(user),
                },
            )
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()
            # messages.success(request, 'Thank you for registering with us. We have sent you a verification email to your email address [rathan.kumar@gmail.com]. Please verify it.')
            return redirect("/accounts/login/?command=verification&email=" + email)
    else:
        form = RegistrationForm()

    ctx = {
        "form": form,
    }

    return render(request, "accounts/register.html", ctx)


def login(request):
    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]

        user = auth.authenticate(email=email, password=password)
        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)
                    # Getting the product variations by cart id
                    product_variation = []

                    for item in cart_item:
                        variation = item.variations.all()
                        product_variation.append(list(variation))

                    # Get the cart items from the user to access his product variations
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variations.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    # product_variation = [1, 2, 3, 4, 6]
                    # ex_var_list = [4, 6, 3, 5]
                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                item.user = user
                                item.save()
            except:
                pass
            auth.login(request, user)
            url = request.META.get("HTTP_REFERER")
            try:
                query = requests.utils.urlparse(url).query
                # print('-->', query)
                # next=/cart/checkout/
                params = dict(x.split("=") for x in query.split("&"))

                if "next" in params:
                    nextPage = params["next"]
                    return redirect(nextPage)
            except:
                return redirect("accounts:dashboard")
        else:
            messages.error(request, "Invalid login credentials")
            return redirect("accounts:login")

    return render(request, "accounts/login.html")


@login_required(login_url="accounts:login")
def logout(request):
    auth.logout(request)
    messages.success(request, "You are logged out.")
    return redirect("accounts:login")


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Congratulations! Your account is activated.")
        return redirect("accounts:login")
    else:
        messages.error(request, "Invalid activation link")
        return redirect("accounts:register")


@login_required(login_url="accounts:login")
def dashboard(request):
    orders = Order.objects.order_by("-created_at").filter(
        user_id=request.user.id, is_ordered=True
    )
    orders_count = orders.count()

    userprofile = UserProfile.objects.get(user_id=request.user.id)
    ctx = {
        "orders_count": orders_count,
        "userprofile": userprofile,
    }
    return render(request, "accounts/dashboard.html", ctx)


def forgotPassword(request):
    if request.method == "POST":
        email = request.POST["email"]
        # when the user is not active, send message and do not go to forgot password
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            # Reset password email
            current_site = get_current_site(request)
            mail_subject = "Reset Your Password"
            message = render_to_string(
                "accounts/reset_password_email.html",
                {
                    "user": user,
                    "domain": current_site,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": default_token_generator.make_token(user),
                },
            )
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(
                request, "Password reset email has been sent to your email address."
            )
            return redirect("accounts:login")
        else:
            messages.error(request, "Account does not exist!")
            return redirect("accounts:forgotPassword")
    return render(request, "accounts/forgotPassword.html")


def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session["uid"] = uid
        messages.success(request, "Please reset your password")
        return redirect("accounts:resetPassword")
    else:
        messages.error(request, "This link has been expired!")
        return redirect("accounts:login")


def resetPassword(request):
    if request.method == "POST":
        password = request.POST["password"]
        confirm_password = request.POST["confirm_password"]

        if password == confirm_password:
            uid = request.session.get("uid")
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, "Password reset successful")
            return redirect("accounts:login")
        else:
            messages.error(request, "Password do not match!")
            return redirect("accounts:resetPassword")
    else:
        return render(request, "accounts/resetPassword.html")


@login_required(login_url="accounts:login")
def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by(
        "-created_at"
    )
    ctx = {
        "orders": orders,
    }
    return render(request, "accounts/my_orders.html", ctx)


@login_required(login_url="accounts:login")
def edit_profile(request):
    userprofile = get_object_or_404(UserProfile, user=request.user)
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(
            request.POST, request.FILES, instance=userprofile
        )

src/category/views.py
from django.shortcuts import render

src/home/views.py
from django.shortcuts import render

from src.store.models import Product, ReviewRating
from src.store.models import Product


def home(request):
    products = Product.objects.all().filter(is_available=True).order_by("created_date")

    # Get the reviews
    reviews = None
    for product in products:
        reviews = ReviewRating.objects.filter(product_id=product.id, status=True)

    ctx = {
        "products": products,
        "reviews": reviews,
    }
    return render(request, "home.html", ctx)

src/store/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator

from src.category.models import Category
from src.carts.models import CartItem
from src.orders.models import OrderProduct

from .models import Product, ReviewRating, ProductGallery
from .forms import ReviewForm

from src.carts.views import _cart_id


def submit_review(request, product_id):
    url = request.META.get("HTTP_REFERER")
    if request.method == "POST":
        try:
            reviews = ReviewRating.objects.get(
                user__id=request.user.id, product__id=product_id
            )
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, "Thank you! Your review has been updated.")
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data["subject"]
                data.rating = form.cleaned_data["rating"]
                data.review = form.cleaned_data["review"]
                data.ip = request.META.get("REMOTE_ADDR")
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, "Thank you! Your review has been submitted.")
                return redirect(url)


def search(request):
    if "search" in request.GET:
        keyword = request.GET["search"]
        if keyword:
            products = Product.objects.order_by("-created_date").filter(
                Q(description__icontains=keyword) | Q(product_name__icontains=keyword)
            )
            product_count = products.count()
    context = {
        "products": products,
        "product_count": product_count,
    }
    return render(request, "store/store.html", context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(
            category__slug=category_slug, slug=product_slug
        )
        in_cart = CartItem.objects.filter(
            cart__cart_id=_cart_id(request), product=single_product
        ).exists()
    except Exception as e:
        raise e

    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(
                user=request.user, product_id=single_product.id
            ).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    # Get the reviews
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)
    
    # Get the product gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {
        "single_product": single_product,
        "in_cart": in_cart,
        "orderproduct": orderproduct,
        "reviews": reviews,
        'product_gallery': product_gallery,
    }
    return render(request, "store/product_detail.html", context)


def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 10)
        page = request.GET.get("page")
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by("id")
        paginator = Paginator(products, 10)
        page = request.GET.get("page")
        paged_products = paginator.get_page(page)
        product_count = products.count()

    ctx = {
        "products": paged_products,
        "product_count": product_count,
    }
    return render(request, "store/store.html", ctx)

src/templates/orders/order_complete.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="container" style="margin-top: 50px;">
  <center>
    <i class="fas fa-check-circle" style="font-size: 72px; margin-bottom: 20px; color: #28a745;"></i>
  </center>
  <h2 class="text-center">Payment Successful</h2>
  <br />
  <div class="text-center">
    <a href="{% url 'store:home' %}" class="btn btn-success">Shop more</a>
  </div>
</div>

<div class="container" style="
    margin: 0 auto;
    width: 50%;
    padding: 50px;
    background: #f1f1f1;
    margin-top: 50px;
    margin-bottom: 50px;
  ">
  <div class="row invoice row-printable">
    <div class="col-md-12">
      <!-- col-lg-12 start here -->
      <div class="panel panel-default plain" id="dash_0">
        <!-- Start .panel -->
        <div class="panel-body p30">
          <div class="row">
            <!-- Start .row -->
            <div class="col-lg-6">
              <!-- col-lg-6 start here -->
              <div class="invoice-logo">
                <img src="{% static '/images/logo.png' %}" alt="Invoice logo" style="max-height: 40px;" />
              </div>
            </div>
            <!-- col-lg-6 end here -->
            <div class="col-lg-6">
              <!-- col-lg-6 start here -->
              <div class="invoice-from">
                <ul class="list-unstyled text-right">
                  <li><strong>Invoiced To</strong></li>
                  <li>{{order.full_name}}</li>
                  <li>{{order.full_address}}</li>
                  <li>{{order.city}}, {{order.state}}</li>
                  <li>{{order.country}}</li>
                </ul>
              </div>
            </div>
            <!-- col-lg-6 end here -->
            <div class="col-lg-12">
              <!-- col-lg-12 start here -->
              <div class="invoice-details mt25">
                <div class="well">
                  <ul class="list-unstyled mb0">
                    <li><strong>Order</strong> #{{order_number}}</li>
                    <li><strong>Transaction ID</strong> {{transID}}</li>
                    <li><strong>Order Date:</strong> {{order.created_at}}</li>
                    <li><strong>Status:</strong> {{payment.status}}</li>
                  </ul>
                </div>
              </div>

              <div class="invoice-items">
                <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th class="per70 text-center">Products</th>
                        <th class="per5 text-center">Qty</th>
                        <th class="per25 text-center">Total</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for item in ordered_products %}
                      <tr>
                        <td>
                          {{item.product.product_name}}
                          <p class="text-muted small">
                            {% if item.variations.all %} 
                              {% for i in item.variations.all %} 
                                {{ i.variation_category | capfirst }} : {{ i.variation_value | capfirst }}
                              <br />
                              {% endfor %}
                            {% endif %}
                          </p>
                        </td>
                        <td class="text-center">{{item.quantity}}</td>
                        <td class="text-center">${{item.product_price}} USD</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                    <tfoot>
                      <tr>
                        <th colspan="2" class="text-right">Sub Total:</th>
                        <th class="text-center">${{subtotal}} USD</th>
                      </tr>
                      <tr>
                        <th colspan="2" class="text-right">Tax:</th>
                        <th class="text-center">${{order.tax}} USD</th>
                      </tr>

                      <tr>
                        <th colspan="2" class="text-right">Grand Total:</th>
                        <th class="text-center">${{order.order_total}} USD</th>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
              <div class="invoice-footer mt25">
                <p class="text-center">Thank you for shopping with us!</p>
              </div>
            </div>
            <!-- col-lg-12 end here -->
          </div>
          <!-- End .row -->
        </div>
      </div>
      <!-- End .panel -->
    </div>
    <!-- col-lg-12 end here -->
  </div>
</div>

{% endblock %}

src/templates/orders/order_recieved_email.html
{% autoescape off %}

Hi {{user.first_name}},

YOUR ORDER HAS BEEN RECIEVED

Order Number: {{order.order_number}}

{% endautoescape %}

src/templates/orders/payments.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section class="section-content padding-y bg">
  <div class="container">
    <h4 class="text-center mb-20">Review Your Order and Make Payment</h4>
    <div class="row">
      <aside class="col-lg-8">
        <div class="card">
          <h5 class="card-header">Billing Address</h5>
          <div class="card-body">
            <p class="card-text mb-0">{{order.full_name}}</p>
            <p class="card-text mb-0">{{order.full_address}}</p>
            <p class="card-text mb-0">{{order.city}}, {{order.state}}</p>
            <p class="card-text mb-0">{{order.country}}</p>
            <p class="card-text mb-0">{{order.email}}</p>
            <p class="card-text mb-0">{{order.phone}}</p>
            {% if order.order_note %}
            <b>Order Note: </b> {{order.order_note}} {% endif %}
          </div>
        </div>
        <div class="card">
          <h5 class="card-header">Payment Method</h5>
          <div class="card-body">
            <p class="card-text">PayPal</p>
          </div>
        </div>
        <div class="card">
          <h5 class="card-header">Review Products</h5>
          <div class="card-body">
            <table class="table table-borderless table-shopping-cart">
              <thead class="text-muted">
                <tr class="small text-uppercase">
                  <th scope="col">Product</th>
                  <th scope="col" width="120">Quantity</th>
                  <th scope="col" width="120">Price</th>
                </tr>
              </thead>
              <tbody>
                {% for cart_item in cart_items %}
                <tr>
                  <td>
                    <figure class="itemside align-items-center">
                      <div class="aside">
                        <img src="{{ cart_item.product.images.url }}" class="img-sm" />
                      </div>
                      <figcaption class="info">
                        <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{
                          cart_item.product.product_name }}</a>
                        <p class="text-muted small">
                          {% if cart_item.variations.all %}
                            {% for item in cart_item.variations.all %}
                              {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }}
                              <br />
                            {% endfor %}
                          {% endif %}
                        </p>
                      </figcaption>
                    </figure>
                  </td>
                  <td>
                    <!-- col.// -->
                    <label for="">{{cart_item.quantity}}</label>
                  </td>
                  <td>
                    <div class="price-wrap">
                      <var class="price">$ {{ cart_item.sub_total }}</var>
                      <small class="text-muted">
                        $ {{ cart_item.product.price }} each
                      </small>
                    </div>
                    <!-- price-wrap .// -->
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </aside>
      <!-- col.// -->
      <aside class="col-lg-4">
        <div class="card">
          <div class="card-body">
            <dl class="dlist-align">
              <dt>Total price:</dt>
              <dd class="text-right">$ {{total}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Tax:</dt>
              <dd class="text-right">$ {{tax}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Grand Total:</dt>
              <dd class="text-right text-dark b">
                <strong>$ {{grand_total}}</strong>
              </dd>
            </dl>
            <hr />
            <p class="text-center mb-3">
              <img src="{% static './images/misc/payments.png' %}" height="26" />
            </p>

            <div id="paypal-button-container">
              <!-- PayPal Button Will Load -->
            </div>
          </div>
          <!-- card-body.// -->
        </div>
        <!-- card.// -->
        <div class="alert alert-danger" role="alert">
          <b>Please Note: </b>This is a demo website. Do not try to make real
          payments.
        </div>
      </aside>
      <!-- col.// -->
    </div>
    <!-- row.// -->
  </div>
  <!-- container .//  -->
</section>

<script>
  // function getCookie(name) {
  //   let cookieValue = null;
  //   if (document.cookie && document.cookie !== "") {
  //     const cookies = document.cookie.split(";");
  //     for (let i = 0; i < cookies.length; i++) {
  //       const cookie = cookies[i].trim();
  //       // Does this cookie string begin with the name we want?
  //       if (cookie.substring(0, name.length + 1) === name + "=") {
  //         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
  //         break;
  //       }
  //     }
  //   }
  //   return cookieValue;
  // }

  // console.log(getCookie("csrftoken"))
  var amount = "{{ grand_total }}";
  var url = "{% url 'orders:payments' %}";
  var csrftoken = "{{ csrf_token }}";
  var orderID = "{{order.order_number}}";
  var payment_method = "PayPal";
  var redirect_url = "{% url 'orders:order_complete' %}"
  //alert()
  // Render the PayPal button into #paypal-button-container
  paypal
    .Buttons({
      style: {
        color: "blue",
        shape: "rect",
        label: "pay",
        height: 40,
      },

      // Set up the transaction
      createOrder: function (data, actions) {
        return actions.order.create({
          purchase_units: [
            {
              amount: {
                value: amount,
              },
            },
          ],
        });
      },

      // Finalize the transaction
      onApprove: function (data, actions) {
        return actions.order.capture().then(function (details) {
          // Show a success message to the buyer
          console.log(details);
          sendData();
          function sendData() {
            fetch(url, {
              method: "POST",
              headers: {
                "Content-type": "application/json",
                "X-CSRFToken": csrftoken,
              },
              body: JSON.stringify({
                orderID: orderID,
                transID: details.id,
                payment_method: payment_method,
                status: details.status,
              }),
            })
              .then((response) => response.json())
              .then((data) => {
                window.location.href =
                  redirect_url +
                  "?order_number=" +
                  data.order_number +
                  "&payment_id=" +
                  data.transID;
              });
          }
        });
      },
    })
    .render("#paypal-button-container");
</script>

{% endblock %}