config/urls.py
"""Main URLs module."""

from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin


# import ipdb; ipdb.set_trace()

urlpatterns = [
    # Django Admin
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include(("src.home.urls", "home"), namespace="home")),
    path("store/", include(("src.store.urls", "store"), namespace="store")),
    path("cart/", include(("src.carts.urls", "cart"), namespace="cart")),
    path("accounts/", include(("src.accounts.urls", "accounts"), namespace="accounts")),
    path("orders/", include(("src.orders.urls", "orders"), namespace="orders")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),


    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),

]

src/carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.cart, name="home"),
    path("add_cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path(
        "remove_cart/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart,
        name="remove_cart",
    ),
    path(
        "remove_cart_item/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
    path('checkout/', views.checkout, name='checkout'),

]

src/home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
]

src/orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("place_order/", views.place_order, name="place_order"),
    path("payments/", views.payments, name="payments"),
    path("order_complete/", views.order_complete, name="order_complete"),
]

src/store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.store, name="home"),
    path("category/<slug:category_slug>/", views.store, name="products_by_category"),
    path(
        "category/<slug:category_slug>/<slug:product_slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path("search/", views.search, name="search"),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),

]

src/store/models.py
from django.db import models
from django.db.models import Avg, Count

from src.category.models import Category
from src.accounts.models import Account
from django.urls import reverse


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to="photos/products", blank=True)
    stock = models.IntegerField(blank=True)
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(
            average=Avg("rating")
        )
        avg = 0
        if reviews["average"] is not None:
            avg = float(reviews["average"])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(
            count=Count("id")
        )
        count = 0
        if reviews["count"] is not None:
            count = int(reviews["count"])
        return count

    def get_url(self):
        return reverse("store:product_detail", args=[self.category.slug, self.slug])


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(
            variation_category="color", is_active=True
        )

    def sizes(self):
        return super(VariationManager, self).filter(
            variation_category="size", is_active=True
        )


variation_category_choice = (
    ("color", "color"),
    ("size", "size"),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(
        max_length=100, choices=variation_category_choice
    )
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="store/products", max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = "productgallery"
        verbose_name_plural = "product gallery"

src/orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "first_name",
            "last_name",
            "phone",
            "email",
            "address_line_1",
            "address_line_2",
            "country",
            "state",
            "city",
            "order_note",
        ]

src/store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ["subject", "review", "rating"]

src/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required

import requests

# Verification email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

from src.carts.views import _cart_id
from src.carts.models import Cart, CartItem
from src.orders.models import Order, OrderProduct

from .models import Account, UserProfile
from .forms import RegistrationForm, UserForm, UserProfileForm


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            phone_number = form.cleaned_data["phone_number"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            username = email.split("@")[0]
            user = Account.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=username,
                password=password,
            )
            user.phone_number = phone_number
            user.save()

            # Create a user profile
            profile = UserProfile()
            profile.user_id = user.id
            profile.profile_picture = "default/default-user.png"
            profile.save()

            # USER ACTIVATION
            current_site = get_current_site(request)
            mail_subject = "Please activate your account"
            message = render_to_string(
                "accounts/account_verification_email.html",
                {
                    "user": user,
                    "domain": current_site,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": default_token_generator.make_token(user),
                },
            )
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()
            # messages.success(request, 'Thank you for registering with us. We have sent you a verification email to your email address [rathan.kumar@gmail.com]. Please verify it.')
            return redirect("/accounts/login/?command=verification&email=" + email)
    else:
        form = RegistrationForm()

    ctx = {
        "form": form,
    }

    return render(request, "accounts/register.html", ctx)


def login(request):
    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]

        user = auth.authenticate(email=email, password=password)
        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)
                    # Getting the product variations by cart id
                    product_variation = []

                    for item in cart_item:
                        variation = item.variations.all()
                        product_variation.append(list(variation))

                    # Get the cart items from the user to access his product variations
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variations.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    # product_variation = [1, 2, 3, 4, 6]
                    # ex_var_list = [4, 6, 3, 5]
                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                item.user = user
                                item.save()
            except:
                pass
            auth.login(request, user)
            url = request.META.get("HTTP_REFERER")
            try:
                query = requests.utils.urlparse(url).query
                # print('-->', query)
                # next=/cart/checkout/
                params = dict(x.split("=") for x in query.split("&"))

                if "next" in params:
                    nextPage = params["next"]
                    return redirect(nextPage)
            except:
                return redirect("accounts:dashboard")
        else:
            messages.error(request, "Invalid login credentials")
            return redirect("accounts:login")

    return render(request, "accounts/login.html")


@login_required(login_url="accounts:login")
def logout(request):
    auth.logout(request)
    messages.success(request, "You are logged out.")
    return redirect("accounts:login")


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Congratulations! Your account is activated.")
        return redirect("accounts:login")
    else:
        messages.error(request, "Invalid activation link")
        return redirect("accounts:register")


@login_required(login_url="accounts:login")
def dashboard(request):
    orders = Order.objects.order_by("-created_at").filter(
        user_id=request.user.id, is_ordered=True
    )
    orders_count = orders.count()

    userprofile = UserProfile.objects.get(user_id=request.user.id)
    ctx = {
        "orders_count": orders_count,
        "userprofile": userprofile,
    }
    return render(request, "accounts/dashboard.html", ctx)


def forgotPassword(request):
    if request.method == "POST":
        email = request.POST["email"]
        # when the user is not active, send message and do not go to forgot password
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            # Reset password email
            current_site = get_current_site(request)
            mail_subject = "Reset Your Password"
            message = render_to_string(
                "accounts/reset_password_email.html",
                {
                    "user": user,
                    "domain": current_site,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": default_token_generator.make_token(user),
                },
            )
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(
                request, "Password reset email has been sent to your email address."
            )
            return redirect("accounts:login")
        else:
            messages.error(request, "Account does not exist!")
            return redirect("accounts:forgotPassword")
    return render(request, "accounts/forgotPassword.html")


def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session["uid"] = uid
        messages.success(request, "Please reset your password")
        return redirect("accounts:resetPassword")
    else:
        messages.error(request, "This link has been expired!")
        return redirect("accounts:login")


def resetPassword(request):
    if request.method == "POST":
        password = request.POST["password"]
        confirm_password = request.POST["confirm_password"]

        if password == confirm_password:
            uid = request.session.get("uid")
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, "Password reset successful")
            return redirect("accounts:login")
        else:
            messages.error(request, "Password do not match!")
            return redirect("accounts:resetPassword")
    else:
        return render(request, "accounts/resetPassword.html")


@login_required(login_url="accounts:login")
def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by(
        "-created_at"
    )
    ctx = {
        "orders": orders,
    }
    return render(request, "accounts/my_orders.html", ctx)


@login_required(login_url="accounts:login")
def edit_profile(request):
    userprofile = get_object_or_404(UserProfile, user=request.user)
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(
            request.POST, request.FILES, instance=userprofile
        )

src/category/views.py
from django.shortcuts import render

src/home/views.py
from django.shortcuts import render

from src.store.models import Product, ReviewRating
from src.store.models import Product


def home(request):
    products = Product.objects.all().filter(is_available=True).order_by("created_date")

    # Get the reviews
    reviews = None
    for product in products:
        reviews = ReviewRating.objects.filter(product_id=product.id, status=True)

    ctx = {
        "products": products,
        "reviews": reviews,
    }
    return render(request, "home.html", ctx)

src/templates/store/cart.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section class="section-content padding-y bg">
  <div class="container">
    {% if not cart_items %}
    <h2 class="text-center">Your Shopping Cart is Empty</h2>
    <br />
    <div class="text-center">
      <a href="{% url 'store:home' %}" class="btn btn-primary"
        >Continue Shopping</a
      >
    </div>
    {% else %}
    <div class="row">
      <aside class="col-lg-9">
        <div class="card">
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Product</th>
                <th scope="col" width="120">Quantity</th>
                <th scope="col" width="120">Price</th>
                <th scope="col" class="text-right" width="200"></th>
              </tr>
            </thead>
            <tbody>
              {% for cart_item in cart_items %}
              <tr>
                <td>
                  <figure class="itemside align-items-center">
                    <div class="aside">
                      <img
                        src="{{ cart_item.product.images.url }}"
                        class="img-sm"
                      />
                    </div>
                    <figcaption class="info">
                      <a
                        href="{{ cart_item.product.get_url }}"
                        class="title text-dark"
                        >{{ cart_item.product.product_name }}</a
                      >
                      <p class="text-muted small">
                        {% if cart_item.variations.all %} 
                          {% for item in cart_item.variations.all %} 
                            {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }}
                        <br />
                          {% endfor %} 
                        {% endif %}
                      </p>
                    </figcaption>
                  </figure>
                </td>
                <td>
                  <!-- col.// -->
                  <div class="col">
                    <div class="input-group input-spinner">
                      <div class="input-group-prepend">
                        <a
                          href="{% url 'cart:remove_cart' cart_item.product.id cart_item.id %}"
                          class="btn btn-light"
                          type="button"
                          id="button-plus"
                        >
                          <i class="fa fa-minus"></i>
                        </a>
                      </div>
                      <input
                        type="text"
                        class="form-control"
                        value="{{ cart_item.quantity }}"
                      />
                      <div class="input-group-append">
                        <form
                          action="{% url 'cart:add_cart' cart_item.product.id %}"
                          method="POST"
                        >
                          {% csrf_token %}
                          {% for item in cart_item.variations.all %}
                            <input
                              type="hidden"
                              name="{{ item.variation_category | lower }}"
                              value="{{ item.variation_value | capfirst }}"
                            />
                          {% endfor %}
                          <button
                            class="btn btn-light"
                            type="submit"
                            id="button-minus"
                          >
                            <i class="fa fa-plus"></i>
                          </button>
                        </form>
                      </div>
                    </div>
                    <!-- input-group.// -->
                  </div>
                  <!-- col.// -->
                  <!-- col.// -->
                </td>
                <td>
                  <div class="price-wrap">
                    <var class="price">$ {{ cart_item.sub_total }}</var>
                    <small class="text-muted">
                      $ {{ cart_item.product.price }} each
                    </small>
                  </div>
                  <!-- price-wrap .// -->
                </td>
                <td class="text-right">
                  <a
                    href="{% url 'cart:remove_cart_item' cart_item.product.id cart_item.id %}"
                    onclick="return confirm('Are you sure you want to delete this item?')"
                    class="btn btn-danger"
                  >
                    Remove</a
                  >
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
      <aside class="col-lg-3">
        <div class="card">
          <div class="card-body">
            <dl class="dlist-align">
              <dt>Total price:</dt>
              <dd class="text-right">$ {{total}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Tax:</dt>
              <dd class="text-right">$ {{tax}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Grand Total:</dt>
              <dd class="text-right text-dark b">
                <strong>$ {{grand_total}}</strong>
              </dd>
            </dl>
            <hr />
            <p class="text-center mb-3">
              <img
                src="{% static './images/misc/payments.png' %}"
                height="26"
              />
            </p>
            <a href="{% url 'cart:checkout' %}" class="btn btn-primary btn-block">
              Checkout
            </a>
            <a href="{% url 'store:home' %}" class="btn btn-light btn-block"
              >Continue Shopping</a
            >
          </div>
          <!-- card-body.// -->
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
    </div>
    <!-- row.// -->
    {% endif %}
  </div>
  <!-- container .//  -->
</section>
{% endblock %}

src/templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
  <div class="container">
    <form action="{% url 'orders:place_order' %}" method="POST">
      {% csrf_token %} 
      <div class="row">
        <aside class="col-lg-6">
          <div class="card">
            <div class="card-body"> 
              <h4 class="card-title mb-4">Billing Address</h4>
                <div class="form-row">
                  <div class="col form-group">
                    <label for="">First Name</label>
                    <input type="text" name="first_name" class="form-control" required>
                  </div>
                  <div class="col form-group">
                    <label for="">Last Name</label>
                    <input type="text" name="last_name" class="form-control" required>
                  </div>
                </div>
                <div class="form-row">
                  <div class="col form-group">
                    <label for="">Email</label>
                    <input type="email" name="email" class="form-control" required>
                  </div>
                  <div class="col form-group">
                    <label for="">Phone Number</label>
                    <input type="text" name="phone" class="form-control" required>
                  </div>
                </div>
                <div class="form-row">
                  <div class="col form-group">
                    <label for="">Address Line 1</label>
                    <input type="text" name="address_line_1" class="form-control" required>
                  </div>
                  <div class="col form-group">
                    <label for="">Address Line 2</label>
                    <input type="text" name="address_line_2" class="form-control">
                  </div>
                </div>
                <div class="form-row">
                  <div class="col form-group">
                    <label for="">City</label>
                    <input type="text" name="city" class="form-control" required>
                  </div>
                  <div class="col form-group">
                    <label for="">State</label>
                    <input type="text" name="state" class="form-control" required>
                  </div>
                  <div class="col form-group">
                    <label for="">Country</label>
                    <input type="text" name="country" class="form-control" required>
                  </div>
                </div>
                <div class="form-row">
                  <label for="">Order Note</label>
                  <textarea name="order_note" rows="2" class="form-control"></textarea>
                </div>

            </div>
          </div> <!-- card.// -->
        </aside> <!-- col.// -->
        <aside class="col-lg-6">

          <div class="card">
            <div class="card-body">
              <table class="table table-borderless table-shopping-cart">
                <thead class="text-muted">
                  <tr class="small text-uppercase">
                    <th scope="col">Product</th>
                    <th scope="col" width="120">Quantity</th>
                    <th scope="col" width="120">Price</th>

                  </tr>
                </thead>
                <tbody>

                  {% for cart_item in cart_items %}
                  <tr>
                    <td>
                      <figure class="itemside align-items-center">
                        <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
                        <figcaption class="info">
                          <a href="{{ cart_item.product.get_url }}" class="title text-dark">
                            {{cart_item.product.product_name }}
                          </a>
                          <p class="text-muted small">
                            {% if cart_item.variations.all %}
                              {% for item in cart_item.variations.all %}
                              {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
                            {% endfor %}
                            {% endif %}
                          </p>
                        </figcaption>
                      </figure>
                    </td>
                    <td>
                      <!-- col.// -->
                      <label for="">{{cart_item.quantity}}</label>
                    </td>
                    <td>
                      <div class="price-wrap">
                        <var class="price">$ {{ cart_item.sub_total }}</var>
                        <small class="text-muted"> $ {{ cart_item.product.price }} each </small>
                      </div> <!-- price-wrap .// -->
                    </td>

                  </tr>
                  {% endfor %}

                </tbody>
              </table>

              <button type="submit" name="submit" class="btn btn-primary btn-block">Place Order</button>
              <a href="{% url 'store:home' %}" class="btn btn-light btn-block">Continue Shopping</a>
              
            </div> <!-- card-body.// -->
          </div> <!-- card.// -->
        </aside> <!-- col.// -->
      </div> <!-- row.// -->
    </form> 
  </div> <!-- container .//  -->
</section>
<!-- 
<script>
  alert(document.cookie)
</script> -->
{% endblock %}