config/urls.py
"""Main URLs module."""

from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin


# import ipdb; ipdb.set_trace()

urlpatterns = [
    # Django Admin
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include(("src.home.urls", "home"), namespace="home")),
    path("store/", include(("src.store.urls", "store"), namespace="store")),
    path("cart/", include(("src.carts.urls", "cart"), namespace="cart")),
    path("accounts/", include(("src.accounts.urls", "accounts"), namespace="accounts")),
    path("orders/", include(("src.orders.urls", "orders"), namespace="orders")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),


    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),

]

src/carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.cart, name="home"),
    path("add_cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path(
        "remove_cart/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart,
        name="remove_cart",
    ),
    path(
        "remove_cart_item/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
    path('checkout/', views.checkout, name='checkout'),

]

src/home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
]

src/store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.store, name="home"),
    path("category/<slug:category_slug>/", views.store, name="products_by_category"),
    path(
        "category/<slug:category_slug>/<slug:product_slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path("search/", views.search, name="search"),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),

]

src/orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "first_name",
            "last_name",
            "phone",
            "email",
            "address_line_1",
            "address_line_2",
            "country",
            "state",
            "city",
            "order_note",
        ]

src/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required

import requests

# Verification email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

from src.carts.views import _cart_id
from src.carts.models import Cart, CartItem
from src.orders.models import Order, OrderProduct

from .models import Account, UserProfile
from .forms import RegistrationForm, UserForm, UserProfileForm


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            phone_number = form.cleaned_data["phone_number"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            username = email.split("@")[0]
            user = Account.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=username,
                password=password,
            )
            user.phone_number = phone_number
            user.save()

            # Create a user profile
            profile = UserProfile()
            profile.user_id = user.id
            profile.profile_picture = "default/default-user.png"
            profile.save()

            # USER ACTIVATION
            current_site = get_current_site(request)
            mail_subject = "Please activate your account"
            message = render_to_string(
                "accounts/account_verification_email.html",
                {
                    "user": user,
                    "domain": current_site,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": default_token_generator.make_token(user),
                },
            )
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()
            # messages.success(request, 'Thank you for registering with us. We have sent you a verification email to your email address [rathan.kumar@gmail.com]. Please verify it.')
            return redirect("/accounts/login/?command=verification&email=" + email)
    else:
        form = RegistrationForm()

    ctx = {
        "form": form,
    }

    return render(request, "accounts/register.html", ctx)


def login(request):
    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]

        user = auth.authenticate(email=email, password=password)
        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)
                    # Getting the product variations by cart id
                    product_variation = []

                    for item in cart_item:
                        variation = item.variations.all()
                        product_variation.append(list(variation))

                    # Get the cart items from the user to access his product variations
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variations.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    # product_variation = [1, 2, 3, 4, 6]
                    # ex_var_list = [4, 6, 3, 5]
                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                item.user = user
                                item.save()
            except:
                pass
            auth.login(request, user)
            url = request.META.get("HTTP_REFERER")
            try:
                query = requests.utils.urlparse(url).query
                # print('-->', query)
                # next=/cart/checkout/
                params = dict(x.split("=") for x in query.split("&"))

                if "next" in params:
                    nextPage = params["next"]
                    return redirect(nextPage)
            except:
                return redirect("accounts:dashboard")
        else:
            messages.error(request, "Invalid login credentials")
            return redirect("accounts:login")

    return render(request, "accounts/login.html")


@login_required(login_url="accounts:login")
def logout(request):
    auth.logout(request)
    messages.success(request, "You are logged out.")
    return redirect("accounts:login")


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Congratulations! Your account is activated.")
        return redirect("accounts:login")
    else:
        messages.error(request, "Invalid activation link")
        return redirect("accounts:register")


@login_required(login_url="accounts:login")
def dashboard(request):
    orders = Order.objects.order_by("-created_at").filter(
        user_id=request.user.id, is_ordered=True
    )
    orders_count = orders.count()

    userprofile = UserProfile.objects.get(user_id=request.user.id)
    ctx = {
        "orders_count": orders_count,
        "userprofile": userprofile,
    }
    return render(request, "accounts/dashboard.html", ctx)


def forgotPassword(request):
    if request.method == "POST":
        email = request.POST["email"]
        # when the user is not active, send message and do not go to forgot password
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            # Reset password email
            current_site = get_current_site(request)
            mail_subject = "Reset Your Password"
            message = render_to_string(
                "accounts/reset_password_email.html",
                {
                    "user": user,
                    "domain": current_site,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": default_token_generator.make_token(user),
                },
            )
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(
                request, "Password reset email has been sent to your email address."
            )
            return redirect("accounts:login")
        else:
            messages.error(request, "Account does not exist!")
            return redirect("accounts:forgotPassword")
    return render(request, "accounts/forgotPassword.html")


def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session["uid"] = uid
        messages.success(request, "Please reset your password")
        return redirect("accounts:resetPassword")
    else:
        messages.error(request, "This link has been expired!")
        return redirect("accounts:login")


def resetPassword(request):
    if request.method == "POST":
        password = request.POST["password"]
        confirm_password = request.POST["confirm_password"]

        if password == confirm_password:
            uid = request.session.get("uid")
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, "Password reset successful")
            return redirect("accounts:login")
        else:
            messages.error(request, "Password do not match!")
            return redirect("accounts:resetPassword")
    else:
        return render(request, "accounts/resetPassword.html")


@login_required(login_url="accounts:login")
def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by(
        "-created_at"
    )
    ctx = {
        "orders": orders,
    }
    return render(request, "accounts/my_orders.html", ctx)


@login_required(login_url="accounts:login")
def edit_profile(request):
    userprofile = get_object_or_404(UserProfile, user=request.user)
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(
            request.POST, request.FILES, instance=userprofile
        )

src/category/views.py
from django.shortcuts import render

src/home/views.py
from django.shortcuts import render

from src.store.models import Product, ReviewRating
from src.store.models import Product


def home(request):
    products = Product.objects.all().filter(is_available=True).order_by("created_date")

    # Get the reviews
    reviews = None
    for product in products:
        reviews = ReviewRating.objects.filter(product_id=product.id, status=True)

    ctx = {
        "products": products,
        "reviews": reviews,
    }
    return render(request, "home.html", ctx)

src/store/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator

from src.category.models import Category
from src.carts.models import CartItem
from src.orders.models import OrderProduct

from .models import Product, ReviewRating, ProductGallery
from .forms import ReviewForm

from src.carts.views import _cart_id


def submit_review(request, product_id):
    url = request.META.get("HTTP_REFERER")
    if request.method == "POST":
        try:
            reviews = ReviewRating.objects.get(
                user__id=request.user.id, product__id=product_id
            )
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, "Thank you! Your review has been updated.")
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data["subject"]
                data.rating = form.cleaned_data["rating"]
                data.review = form.cleaned_data["review"]
                data.ip = request.META.get("REMOTE_ADDR")
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, "Thank you! Your review has been submitted.")
                return redirect(url)


def search(request):
    if "search" in request.GET:
        keyword = request.GET["search"]
        if keyword:
            products = Product.objects.order_by("-created_date").filter(
                Q(description__icontains=keyword) | Q(product_name__icontains=keyword)
            )
            product_count = products.count()
    context = {
        "products": products,
        "product_count": product_count,
    }
    return render(request, "store/store.html", context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(
            category__slug=category_slug, slug=product_slug
        )
        in_cart = CartItem.objects.filter(
            cart__cart_id=_cart_id(request), product=single_product
        ).exists()
    except Exception as e:
        raise e

    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(
                user=request.user, product_id=single_product.id
            ).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    # Get the reviews
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)
    
    # Get the product gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {
        "single_product": single_product,
        "in_cart": in_cart,
        "orderproduct": orderproduct,
        "reviews": reviews,
        'product_gallery': product_gallery,
    }
    return render(request, "store/product_detail.html", context)


def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 10)
        page = request.GET.get("page")
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by("id")
        paginator = Paginator(products, 10)
        page = request.GET.get("page")
        paged_products = paginator.get_page(page)
        product_count = products.count()

    ctx = {
        "products": paged_products,
        "product_count": product_count,
    }
    return render(request, "store/store.html", ctx)

src/templates/accounts/account_verification_email.html
{% autoescape off %} 

Hi {{user.first_name}}, 

Please click on below link to confirm your registration. 
http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %} 

If you think it's not you, please ignore this email. 

{% endautoescape %}

src/templates/accounts/change_password.html
{% extends 'base.html' %} 
{% block content %}

<section class="section-conten padding-y bg">
  {% include 'includes/alerts.html' %}
  <div class="container">
    <div class="row">
      {% include 'includes/dashboard_sidebar.html' %}
      <main class="col-md-9">
        <article class="card">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Change Your Password</strong>
          </header>
          <div class="card-body">
            <div class="row">
              <div class="col-md-12">
                <form action="{% url 'accounts:change_password' %}" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label>Current Password</label>
                    <input type="password" name="current_password" placeholder="Current Password" class="form-control"
                      required />
                  </div>
                  <div class="form-group">
                    <label>Create new password</label>
                    <input type="password" name="new_password" placeholder="Create New Password" class="form-control"
                      required />
                  </div>
                  <div class="form-group">
                    <label>Confirm new password</label>
                    <input type="password" name="confirm_password" placeholder="Confirm New Password"
                      class="form-control" required />
                  </div>

                  <input type="submit" value="Submit" class="btn btn-primary" />
                </form>
              </div>
            </div>
            <!-- row.// -->
          </div>
          <!-- card-body .// -->
        </article>
        <!-- order-group.// -->
      </main>
    </div>
    <!-- row.// -->
  </div>
</section>

{% endblock %}

src/templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block content %}
<section class="section-conten padding-y bg">

  {% include 'includes/alerts.html' %}
  <div class="container">
    <div class="row">
      {% include 'includes/dashboard_sidebar.html' %}
      <main class="col-md-9">
        <article class="card">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Logged in as:</strong>
            <span>{{user.full_name}}</span>
          </header>
          <div class="card-body">
            <div class="row">

              <div class="col-md-6">
                <div class="card" style="text-align:center;">
                  <div class="card-body">
                    <h5 class="card-title">Total Orders</h5>
                    <h4>{{orders_count}}</h4>
                    <a href="{% url 'accounts:my_orders' %}">View Orders</a>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="card" style="text-align:center;">
                  <div class="card-body">
                    <img src="{{userprofile.profile_picture.url}}" alt="User Profile Picture" width="50" height="50"
                      style="border-radius:50%;">
                    <p class="mb-0">{{user.email}}</p>
                    <p>{{user.phone_number}}</p>
                  </div>
                </div>
              </div>
            </div> <!-- row.// -->
          </div> <!-- card-body .// -->

        </article> <!-- order-group.// -->
      </main>
    </div> <!-- row.// -->
  </div>
</section>

{% endblock %}

src/templates/accounts/edit_profile.html
{% extends 'base.html' %} 
{% block content %}

<section class="section-conten padding-y bg">
  {% include 'includes/alerts.html' %}
  <div class="container">
    <div class="row">
      {% include 'includes/dashboard_sidebar.html' %}
      <main class="col-md-9">
        <article class="card">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Edit your profile</strong>
          </header>
          <div class="card-body">
            <div class="text-right">
              <img
                src="{{userprofile.profile_picture.url}}"
                alt="Profile Picture"
                width="100"
                style="border-radius: 50px;"
              />
            </div>
            <div class="row">
              <div class="col-md-12">
                <form
                  action="{% url 'accounts:edit_profile' %}"
                  method="POST"
                  enctype="multipart/form-data"
                >
                  {% csrf_token %}
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>First Name</label>
                      {{user_form.first_name}}
                    </div>
                    <div class="form-group col-md-6">
                      <label>Last Name</label>
                      {{user_form.last_name}}
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>Phone Number</label>
                      {{user_form.phone_number}}
                    </div>
                    <div class="form-group col-md-6">
                      <label>Profile Picture</label>
                      {{profile_form.profile_picture}}
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Address Line 1</label>
                    {{profile_form.address_line_1}}
                  </div>
                  <div class="form-group">
                    <label>Address Line 2</label>
                    {{profile_form.address_line_2}}
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-4">
                      <label>City</label>
                      {{profile_form.city}}
                    </div>
                    <div class="form-group col-md-4">
                      <label>State</label>
                      {{profile_form.state}}
                    </div>
                    <div class="form-group col-md-4">
                      <label>Country</label>
                      {{profile_form.country}}
                    </div>
                  </div>
                  <input type="submit" value="Save" class="btn btn-primary" />
                </form>
              </div>
            </div>
            <!-- row.// -->
          </div>
          <!-- card-body .// -->
        </article>
        <!-- order-group.// -->
      </main>
    </div>
    <!-- row.// -->
  </div>
</section>

{% endblock %}

src/templates/accounts/forgotPassword.html
{% extends 'base.html' %}
{% block content %}
<section class="section-conten padding-y" style="min-height: 84vh;">
  <div class="card mx-auto" style="max-width: 600px; margin-top: 100px;">
    <div class="card-body">
      <h4 class="card-title mb-4">Forgot Password</h4>
      {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:forgotPassword' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <input
            type="email"
            class="form-control"
            placeholder="Email Address"
            name="email"
          />
        </div>
        <!-- form-group// -->

        <div class="form-group">
          <a href="{% url 'accounts:login' %}" class="float-right"
            >Got password? Login</a
          >
        </div>
        <!-- form-group form-check .// -->
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">
            Submit
          </button>
        </div>
        <!-- form-group// -->
      </form>
    </div>
    <!-- card-body.// -->
  </div>
  <!-- card .// -->
  
  <p class="text-center mt-4">
    Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a>
  </p>
  <br /><br />
</section>
{% endblock %}

src/templates/accounts/login.html
{% extends 'base.html' %} {% block content %}

<section class="section-conten padding-y" style="min-height: 84vh;">
  
  {% if request.GET.command == 'verification' %}

  <div
    class="container mx-auto alert alert-info text-center"
    role="alert"
    style="max-width: 1024px; margin-top: 100px;"
  >
    Thank you for registering with us. We have sent you a verification email to
    your email address [{{ request.GET.email }}]
    <br /><br />
    Already verified? <a href="{% url 'accounts:login' %}">Login</a>
  </div>

  {% else %}

  <div class="card mx-auto" style="max-width: 380px; margin-top: 100px;">
    <div class="card-body">
      <h4 class="card-title mb-4">Sign in</h4>
      {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <input
            type="email"
            class="form-control"
            placeholder="Email Address"
            name="email"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group">
          <input
            type="password"
            class="form-control"
            placeholder="Password"
            name="password"
          />
        </div>
        <!-- form-group// -->

        <div class="form-group">
          <a href="{% url 'accounts:forgotPassword' %}" class="float-right">Forgot password?</a>
        </div>
        <!-- form-group form-check .// -->
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">Login</button>
        </div>
        <!-- form-group// -->
      </form>
    </div>
    <!-- card-body.// -->
  </div>
  <!-- card .// -->

  <p class="text-center mt-4">
    Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a>
  </p>
  <br /><br />
  {% endif %}
</section>
{% endblock %}

src/templates/accounts/my_orders.html
{% extends 'base.html' %} 
{% block content %}

<section class="section-conten padding-y bg">
  {% include 'includes/alerts.html' %}
  <div class="container">
    <div class="row">
      {% include 'includes/dashboard_sidebar.html' %}
      <main class="col-md-9">
        <article class="card">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Your order history</strong>
          </header>
          <div class="card-body">
            <div class="row">
              <div class="col-md-12">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">Order #</th>
                      <th scope="col">Billing Name</th>
                      <th scope="col">Phone</th>
                      <th scope="col">Order Total</th>
                      <th scope="col">Date</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for order in orders %}
                    <tr>
                      <th scope="row">
                        <a href="{% url 'accounts:order_detail' order.order_number %}">{{order.order_number}}</a>
                      </th>
                      <td>{{order.full_name}}</td>
                      <td>{{order.phone}}</td>
                      <td>${{order.order_total}}</td>
                      <td>{{order.created_at}}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
            <!-- row.// -->
          </div>
          <!-- card-body .// -->
        </article>
        <!-- order-group.// -->
      </main>
    </div>
    <!-- row.// -->
  </div>
</section>

{% endblock %}

src/templates/accounts/resetPassword.html
{% extends 'base.html' %} 
{% block content %}
<section class="section-conten padding-y" style="min-height: 84vh;">

  <div class="card mx-auto" style="max-width: 380px; margin-top: 100px;">
    <div class="card-body">
      <h4 class="card-title mb-4">Reset Password</h4>
      {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:resetPassword' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <input
            type="password"
            class="form-control"
            placeholder="Create Password"
            name="password"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group">
          <input
            type="password"
            class="form-control"
            placeholder="Confirm Password"
            name="confirm_password"
          />
        </div>
        <!-- form-group// -->

        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">Reset</button>
        </div>
        <!-- form-group// -->
      </form>
    </div>
    <!-- card-body.// -->
  </div>
  <!-- card .// -->

  <p class="text-center mt-4">
    Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a>
  </p>
  <br /><br />
</section>
{% endblock %}

src/templates/accounts/reset_password_email.html
{% autoescape off %} 

Hi {{user.first_name}}, 

As requested, please click below link to reset your password. 

http://{{domain}}{% url 'accounts:resetpassword_validate' uidb64=uid token=token %} 

If you think it's not you, please ignore this email.
{% endautoescape %}