config/urls.py
"""Main URLs module."""

from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin


# import ipdb; ipdb.set_trace()

urlpatterns = [
    # Django Admin
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include(("src.home.urls", "home"), namespace="home")),
    path("store/", include(("src.store.urls", "store"), namespace="store")),
    path("cart/", include(("src.carts.urls", "cart"), namespace="cart")),
    path("accounts/", include(("src.accounts.urls", "accounts"), namespace="accounts")),
    path("orders/", include(("src.orders.urls", "orders"), namespace="orders")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),


    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),

]

src/carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.cart, name="home"),
    path("add_cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path(
        "remove_cart/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart,
        name="remove_cart",
    ),
    path(
        "remove_cart_item/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
    path('checkout/', views.checkout, name='checkout'),

]

src/home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
]

src/store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.store, name="home"),
    path("category/<slug:category_slug>/", views.store, name="products_by_category"),
    path(
        "category/<slug:category_slug>/<slug:product_slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path("search/", views.search, name="search"),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),

]

src/orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "first_name",
            "last_name",
            "phone",
            "email",
            "address_line_1",
            "address_line_2",
            "country",
            "state",
            "city",
            "order_note",
        ]

src/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required

import requests

# Verification email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

from src.carts.views import _cart_id
from src.carts.models import Cart, CartItem
from src.orders.models import Order, OrderProduct

from .models import Account, UserProfile
from .forms import RegistrationForm, UserForm, UserProfileForm


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            phone_number = form.cleaned_data["phone_number"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            username = email.split("@")[0]
            user = Account.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=username,
                password=password,
            )
            user.phone_number = phone_number
            user.save()

            # Create a user profile
            profile = UserProfile()
            profile.user_id = user.id
            profile.profile_picture = "default/default-user.png"
            profile.save()

            # USER ACTIVATION
            current_site = get_current_site(request)
            mail_subject = "Please activate your account"
            message = render_to_string(
                "accounts/account_verification_email.html",
                {
                    "user": user,
                    "domain": current_site,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": default_token_generator.make_token(user),
                },
            )
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()
            # messages.success(request, 'Thank you for registering with us. We have sent you a verification email to your email address [rathan.kumar@gmail.com]. Please verify it.')
            return redirect("/accounts/login/?command=verification&email=" + email)
    else:
        form = RegistrationForm()

    ctx = {
        "form": form,
    }

    return render(request, "accounts/register.html", ctx)


def login(request):
    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]

        user = auth.authenticate(email=email, password=password)
        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)
                    # Getting the product variations by cart id
                    product_variation = []

                    for item in cart_item:
                        variation = item.variations.all()
                        product_variation.append(list(variation))

                    # Get the cart items from the user to access his product variations
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variations.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    # product_variation = [1, 2, 3, 4, 6]
                    # ex_var_list = [4, 6, 3, 5]
                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                item.user = user
                                item.save()
            except:
                pass
            auth.login(request, user)
            url = request.META.get("HTTP_REFERER")
            try:
                query = requests.utils.urlparse(url).query
                # print('-->', query)
                # next=/cart/checkout/
                params = dict(x.split("=") for x in query.split("&"))

                if "next" in params:
                    nextPage = params["next"]
                    return redirect(nextPage)
            except:
                return redirect("accounts:dashboard")
        else:
            messages.error(request, "Invalid login credentials")
            return redirect("accounts:login")

    return render(request, "accounts/login.html")


@login_required(login_url="accounts:login")
def logout(request):
    auth.logout(request)
    messages.success(request, "You are logged out.")
    return redirect("accounts:login")


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Congratulations! Your account is activated.")
        return redirect("accounts:login")
    else:
        messages.error(request, "Invalid activation link")
        return redirect("accounts:register")


@login_required(login_url="accounts:login")
def dashboard(request):
    orders = Order.objects.order_by("-created_at").filter(
        user_id=request.user.id, is_ordered=True
    )
    orders_count = orders.count()

    userprofile = UserProfile.objects.get(user_id=request.user.id)
    ctx = {
        "orders_count": orders_count,
        "userprofile": userprofile,
    }
    return render(request, "accounts/dashboard.html", ctx)


def forgotPassword(request):
    if request.method == "POST":
        email = request.POST["email"]
        # when the user is not active, send message and do not go to forgot password
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            # Reset password email
            current_site = get_current_site(request)
            mail_subject = "Reset Your Password"
            message = render_to_string(
                "accounts/reset_password_email.html",
                {
                    "user": user,
                    "domain": current_site,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": default_token_generator.make_token(user),
                },
            )
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(
                request, "Password reset email has been sent to your email address."
            )
            return redirect("accounts:login")
        else:
            messages.error(request, "Account does not exist!")
            return redirect("accounts:forgotPassword")
    return render(request, "accounts/forgotPassword.html")


def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session["uid"] = uid
        messages.success(request, "Please reset your password")
        return redirect("accounts:resetPassword")
    else:
        messages.error(request, "This link has been expired!")
        return redirect("accounts:login")


def resetPassword(request):
    if request.method == "POST":
        password = request.POST["password"]
        confirm_password = request.POST["confirm_password"]

        if password == confirm_password:
            uid = request.session.get("uid")
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, "Password reset successful")
            return redirect("accounts:login")
        else:
            messages.error(request, "Password do not match!")
            return redirect("accounts:resetPassword")
    else:
        return render(request, "accounts/resetPassword.html")


@login_required(login_url="accounts:login")
def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by(
        "-created_at"
    )
    ctx = {
        "orders": orders,
    }
    return render(request, "accounts/my_orders.html", ctx)


@login_required(login_url="accounts:login")
def edit_profile(request):
    userprofile = get_object_or_404(UserProfile, user=request.user)
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(
            request.POST, request.FILES, instance=userprofile
        )

src/category/views.py
from django.shortcuts import render

src/home/views.py
from django.shortcuts import render

from src.store.models import Product, ReviewRating
from src.store.models import Product


def home(request):
    products = Product.objects.all().filter(is_available=True).order_by("created_date")

    # Get the reviews
    reviews = None
    for product in products:
        reviews = ReviewRating.objects.filter(product_id=product.id, status=True)

    ctx = {
        "products": products,
        "reviews": reviews,
    }
    return render(request, "home.html", ctx)

src/store/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator

from src.category.models import Category
from src.carts.models import CartItem
from src.orders.models import OrderProduct

from .models import Product, ReviewRating, ProductGallery
from .forms import ReviewForm

from src.carts.views import _cart_id


def submit_review(request, product_id):
    url = request.META.get("HTTP_REFERER")
    if request.method == "POST":
        try:
            reviews = ReviewRating.objects.get(
                user__id=request.user.id, product__id=product_id
            )
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, "Thank you! Your review has been updated.")
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data["subject"]
                data.rating = form.cleaned_data["rating"]
                data.review = form.cleaned_data["review"]
                data.ip = request.META.get("REMOTE_ADDR")
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, "Thank you! Your review has been submitted.")
                return redirect(url)


def search(request):
    if "search" in request.GET:
        keyword = request.GET["search"]
        if keyword:
            products = Product.objects.order_by("-created_date").filter(
                Q(description__icontains=keyword) | Q(product_name__icontains=keyword)
            )
            product_count = products.count()
    context = {
        "products": products,
        "product_count": product_count,
    }
    return render(request, "store/store.html", context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(
            category__slug=category_slug, slug=product_slug
        )
        in_cart = CartItem.objects.filter(
            cart__cart_id=_cart_id(request), product=single_product
        ).exists()
    except Exception as e:
        raise e

    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(
                user=request.user, product_id=single_product.id
            ).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    # Get the reviews
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)
    
    # Get the product gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {
        "single_product": single_product,
        "in_cart": in_cart,
        "orderproduct": orderproduct,
        "reviews": reviews,
        'product_gallery': product_gallery,
    }
    return render(request, "store/product_detail.html", context)


def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 10)
        page = request.GET.get("page")
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by("id")
        paginator = Paginator(products, 10)
        page = request.GET.get("page")
        paged_products = paginator.get_page(page)
        product_count = products.count()

    ctx = {
        "products": paged_products,
        "product_count": product_count,
    }
    return render(request, "store/store.html", ctx)

src/templates/includes/alert.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div id="message" class="container">
        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
            <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
            {{ message }}
        </div>
    </div>
    {% endfor %}
</ul>
{% endif %}

src/templates/includes/alerts.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div id="message" class="container">
        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
            <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
            {{ message }}
        </div>
    </div>
    {% endfor %}
</ul>
{% endif %}

src/templates/includes/dashboard_sidebar.html
<aside class="col-md-3">
  <ul class="list-group">
    <a class="list-group-item {% if '/accounts/' == request.path %}active{% endif %}"
      href="{% url 'accounts:dashboard' %}">
      Dashboard
    </a>
    <a class="list-group-item {% if '/my_orders/' in request.path %}active{% endif %}"
      href="{% url 'accounts:my_orders' %}">
      My Orders
    </a>
    <a class="list-group-item {% if '/edit_profile/' in request.path %}active{% endif %}"
      href="{% url 'accounts:edit_profile' %}">
      Edit Profile
    </a>
    <a class="list-group-item {% if '/change_password/' in request.path %}active{% endif %}"
      href="{% url 'accounts:change_password' %}">
      Change Password
    </a>
  </ul>
  <br />
  <a class="btn btn-light btn-block" href="{% url 'accounts:logout' %}">
    <i class="fa fa-power-off"></i> <span class="text">Log out</span>
  </a>
</aside>

src/templates/includes/footer.html
<footer class="section-footer border-top">
  <div class="container">
    <section class="footer-bottom border-top row">
      <div class="col-md-2">
        <span>© <span id="yearf"></span> Nestor Monroy</span>
      </div>
      <div class="col-md-8 text-md-center">
        <span class="px-2">info@pixsellz.io</span>
        <span class="px-2">+879-332-9375</span>
        <span class="px-2">Street name 123, Avanue abc</span>
      </div>
      <div class="col-md-2 text-md-right text-muted">
        <i class="fab fa-lg fa-cc-visa"></i>
        <i class="fab fa-lg fa-cc-paypal"></i>
        <i class="fab fa-lg fa-cc-mastercard"></i>
      </div>
    </section>
  </div>
  <!-- //container -->
</footer>

src/templates/includes/navbar.html
{% load static %}

<header class="section-header">
  <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
    <div class="container">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarTop4"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTop4">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a href="#" class="nav-link"> English </a>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link"> USD </a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li>
            <a href="#" class="nav-link">
              <i class="fa fa-envelope"></i> Email
            </a>
          </li>
          <li>
            <a href="#" class="nav-link">
              <i class="fa fa-phone"></i> Call us
            </a>
          </li>
        </ul>
        <!-- list-inline //  -->
      </div>
      <!-- navbar-collapse .// -->
    </div>
    <!-- container //  -->
  </nav>

  <section class="header-main border-bottom">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
          <a href="{% url 'home:home' %}" class="brand-wrap">
            <img class="logo" src="{% static './images/logo.png' %}" />
          </a>
          <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
          <div class="category-wrap dropdown d-inline-block float-right">
            <button
              type="button"
              class="btn btn-primary dropdown-toggle"
              data-toggle="dropdown"
            >
              <i class="fa fa-bars"></i> All category
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'store:home' %}">
                All Products</a
              >
              {% for category in links %}
              <a class="dropdown-item" href="{{ category.get_url }}"
                >{{ category.category_name }}
              </a>
              {% endfor %}
            </div>
          </div>
          <!-- category-wrap.// -->
        </div>
        <!-- col.// -->
        <a href="{% url 'store:home' %}" class="btn btn-outline-primary"
          >Store</a
        >
        <div class="col-lg col-md-6 col-sm-12 col">
          <form action="{% url 'store:search' %}" class="search" method="GET">
            <div class="input-group w-100">
              <input
                type="text"
                class="form-control"
                style="width: 60%;"
                placeholder="Search"
                name="search"
                required
              />

              <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                  <i class="fa fa-search"></i>
                </button>
              </div>
            </div>
          </form>
          <!-- search-wrap .end// -->
          <!-- search-wrap .end// -->
        </div>
        <!-- col.// -->

        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
          <div class="d-flex justify-content-end mb-3 mb-lg-0">
            {% if user.id is None %}
            <div class="widget-header">
              <small class="title text-muted">Welcome guest!</small>
              <div>
                <a href="{% url 'accounts:login' %}">Sign in</a>
                <span class="dark-transp"> | </span>
                <a href="{% url 'accounts:register' %}"> Register</a>
              </div>
            </div>
            {% else %}
            <div class="widget-header">
              <small class="title text-muted"
                >Welcome {{user.first_name}}!</small
              >
              <div>
                <a href="{% url 'accounts:dashboard' %}">Dashboard</a>
                <span class="dark-transp"> | </span>
                <a href="{% url 'accounts:logout' %}"> Logout</a>
              </div>
            </div>
            {% endif %}
            <a href="{% url 'cart:home' %}" class="widget-header pl-3 ml-3">
              <div class="icon icon-sm rounded-circle border">
                <i class="fa fa-shopping-cart"></i>
              </div>
              <span class="badge badge-pill badge-danger notify"
                >{{cart_count}}</span
              >
            </a>
          </div>
          <!-- widgets-wrap.// -->
        </div>
        <!-- col.// -->
      </div>
      <!-- row.// -->
    </div>
    <!-- container.// -->
  </section>
  <!-- header-main .// -->
</header>
<!-- section-header.// -->